### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gugav10** [ditokapanadze/sqlApp#9]
- [ ] მოდულების კონფიგურაციების config ფოლდერში დამოუკიდებლად გატანა (decoupling), მაგალითად setupExpress რომელიც app.js ში გამოიძახე main ფუნქციაში (ამაზე ვისაუბროთ ეს რატომაა კარგი).
- [ ] Error handling ის გაუმჯობესება, მაგალითი https://github.com/Hammerten/ticket/tree/main/auth/src/libs/errors
- [x] ლოგირება Winston ით 
- [ ] დოკერიზაცია
- [x] მედია სერვისი (S3)
- [ ] deployment (container cloud instance)
- [ ]  Unit tests
- [ ]  Integration tests (e2e)
